"use strict";
// Snapshot the current Herdr tab state into `projects/workspace-state.toml`,
// the source of truth for the startup restore.
//
// This reads the live state via getWorkspaceState()
// (src/utils/workspace-state.js) and renders the full cross-space layout.
// The state file is rewritten untouched on every event/cd -- never hand-edit
// it. The previous snapshot is rotated to `workspace-state.prev.toml` first,
// so one bad write never destroys the last good state silently.
//
// Usage:
//     node src/snapshot.js            # write the state file (events, cd hook,
//                                      # capture action)
//     node src/snapshot.js --stdout   # preview, write nothing

const fs = require("node:fs");
const path = require("node:path");
const { tomlString } = require("./utils/toml");
const { getWorkspaceState, shortenHome, utcStamp } = require("./utils/workspace-state");
const { resolveConfigDir } = require("./utils/config");
const { ProjectError } = require("./utils/project");

const PROJECTS_DIR_NAME = "projects";
// The single state file: every event and shell cd rewrites the full live
// state here, so the live layout survives in a file.
const STATE_NAME = "workspace-state";

class SnapshotError extends Error {}

function expandHomeOnly(p) {
  // State entries carry at most a leading `~` (from shortenHome); no $VARS
  // are ever introduced, so only `~` needs expanding for the common-ancestor
  // computation.
  const home = process.env.HOME || "";
  if (p === "~") return home;
  if (home && p.startsWith("~/")) return home + p.slice(1);
  return p;
}

function parseArgs(argv) {
  const args = { stdout: false };
  for (const arg of argv) {
    if (arg === "--stdout") args.stdout = true;
    else {
      console.error(`snapshot: error: unrecognized arguments: ${arg}`);
      return null;
    }
  }
  return args;
}

// Longest common ancestor directory of absolute paths ("/" when unrelated).
function commonAncestor(dirs) {
  const split = dirs.map((d) => d.split("/").filter((s) => s !== ""));
  let common = split[0];
  for (const parts of split.slice(1)) {
    let i = 0;
    while (i < common.length && i < parts.length && common[i] === parts[i]) i++;
    common = common.slice(0, i);
  }
  return "/" + common.join("/");
}

// Group flat workspace state into Map<label, rows[]> for collectProjectTabs.
function groupByLabel(state) {
  const rowsByLabel = new Map();
  for (const { workspace, label, cwd } of state) {
    if (!rowsByLabel.has(label)) rowsByLabel.set(label, []);
    rowsByLabel.get(label).push({ workspace, label, cwd });
  }
  return rowsByLabel;
}

// Flatten live rows into project tabs, skipping what a state file cannot
// express. Grouped by (workspace, label): the same label may appear once per
// space, each keeping its own `workspace`. Returns { tabs, warnings } with
// ~-abbreviated working dirs, sorted by workspace then label.
function collectProjectTabs(rowsByLabel) {
  const groups = new Map();
  for (const rows of rowsByLabel.values()) {
    for (const row of rows) {
      const key = `${row.workspace}	${row.label}`;
      if (!groups.has(key)) groups.set(key, { workspace: row.workspace, label: row.label, rows: [] });
      groups.get(key).rows.push(row);
    }
  }
  const tabs = [];
  const warnings = [];
  for (const key of [...groups.keys()].sort()) {
    const { workspace, label, rows } = groups.get(key);
    const distinctCwds = [...new Set(rows.map((r) => r.cwd))].sort();
    if (distinctCwds.length > 1) {
      warnings.push(
        `skipping '${label}' in workspace '${workspace}' (${distinctCwds.length} ` +
          "different directories); rename the tab and re-snapshot"
      );
      continue;
    }
    if (!rows[0].cwd) {
      warnings.push(`skipping tab '${label}' (no readable working directory)`);
      continue;
    }
    tabs.push({ name: label, workspace, workingDir: rows[0].cwd });
  }
  return { tabs, warnings };
}

function renderProject(baseOut, tabs) {
  const lines = [
    `# Generated by herdr-cwd-restore snapshot from live tab state (${utcStamp()}).`,
    "# Mirror of the live layout for the startup restore -- do not hand-edit,",
    "# it is rewritten untouched on every event and cd.",
    "",
    `name = ${tomlString(STATE_NAME)}`,
    `working_dir = ${tomlString(baseOut)}`,
    "",
  ];
  for (const tab of tabs) {
    lines.push("[[tabs]]");
    lines.push(`name = ${tomlString(tab.name)}`);
    if (tab.workspace) lines.push(`workspace = ${tomlString(tab.workspace)}`);
    if (tab.workingDir !== null) lines.push(`working_dir = ${tomlString(tab.workingDir)}`);
    lines.push("");
  }
  return lines.join("\n").replace(/\s+$/, "") + "\n";
}

// Best-effort rotation: keep the previous snapshot beside the target
// (`workspace-state.toml` -> `workspace-state.prev.toml`) so one bad write
// -- e.g. the first event after a degraded Herdr restore -- never destroys
// the last good state silently. Failures only warn; the snapshot proceeds.
function rotateBackup(out) {
  let prev;
  if (out.endsWith(".toml")) prev = out.slice(0, -5) + ".prev.toml";
  else prev = `${out}.prev`;
  try {
    if (fs.statSync(out).isFile()) {
      fs.copyFileSync(out, prev);
    }
  } catch (error) {
    console.error(`snapshot: warning: could not rotate backup ${prev}: ${error.message}`);
  }
}

function main(argv) {
  const args = parseArgs(argv);
  if (args === null) return 2;
  try {
    const rowsByLabel = groupByLabel(getWorkspaceState());
    const { tabs, warnings } = collectProjectTabs(rowsByLabel);
    if (tabs.length === 0) {
      throw new SnapshotError("no snapshotable tabs open (nothing to snapshot)");
    }
    const expanded = tabs.map((t) => expandHomeOnly(t.workingDir));
    const baseOut = shortenHome(commonAncestor(expanded));
    const baseExpanded = expandHomeOnly(baseOut);
    for (const tab of tabs) {
      if (expandHomeOnly(tab.workingDir) === baseExpanded) tab.workingDir = null;
    }
    const text = renderProject(baseOut, tabs);
    for (const warning of warnings) console.error(`snapshot: warning: ${warning}`);
    if (args.stdout) {
      process.stdout.write(text);
      return 0;
    }
    const out = path.join(resolveConfigDir(), PROJECTS_DIR_NAME, `${STATE_NAME}.toml`);
    fs.mkdirSync(path.dirname(out), { recursive: true });
    rotateBackup(out);
    fs.writeFileSync(out, text);
    console.error(`snapshot: wrote ${tabs.length} tab(s) into ${out}`);
    return 0;
  } catch (error) {
    if (error instanceof SnapshotError || error instanceof ProjectError) {
      console.error(`snapshot: ${error.message}`);
      return 1;
    }
    throw error;
  }
}

if (require.main === module) {
  process.exit(main(process.argv.slice(2)));
}

module.exports = {
  parseArgs,
  groupByLabel,
  collectProjectTabs,
  commonAncestor,
  renderProject,
  rotateBackup,
  SnapshotError,
};
